# Generated by Django 3.2.3 on 2021-05-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='custom_drink',
            field=models.BooleanField(default=False),
        ),
    ]
